
export const START_LOGIN_FETCHING = "START_LOGIN_FETCHING";
export const SUCCESS_LOGIN_FETCHING = "SUCCESS_LOGIN_FETCHING";
export const ERROR_LOGIN_FETCHING = "ERROR_LOGIN_FETCHING";
export const LOGOUT = "LOGOUT";
